# CMake using google-test
How to add unit test to a project using the GoogleTesting framework. We'll use FetchContent for that purpose.

:toc:
:sectnums:

== Introduction
In this article, we'll talk about using the `FetchContent` module to fetch, download and use the `Google test` framework that is used to making some test for our C++ application.

Indeed, we are going to make use of some third-party libraries for testing purposes, libraries such as `GoogleTest` need to be fetched by your build system in order to link against your project and use it when you need it.

== Pull the GoogleTest
In order to use `GoogleTest` to your application, you'll need to pull the `GoogleTest` library from the internet, and we'll use `FetchContent` module for that:

```cmake
include(FetchContent)
FetchContent_Declare(
    googletest 
    GIT_REPOSITORY https://github.com/google/googletest.git
    GIT_TAG v1.14.0
)
```

NOTE: The `FetchContent_Declare` first parameter isn't the name of the module, it's more like the name of the module that is used in your build system

```cmake
# For windows: Prevent overriding the parent project's compiler/linker
set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(googletest)
```

NOTE: You can see that the name you defined in the `FetchContent_Declare` function is used inside of the `FetchContent_MakeAvailable`. Also, the set is due to the documentation of GoogleTest.

=== Enable testing
Once you did use the `FetchContent` module to fetch GTest from the internet, you should (in you main CMakeLists.txt) enable the testing, that can be done through the following command

```cmake
cmake_minimum_required(VERSION <version>)
...
enable_testing()
...
```
Using the `enable_testing` command in your main CMake of your app will enable testing for current direcrory and below.

NOTE: This command should be in top-level source directory because `ctest` expects to find a test file in the top-level build directory. This command is automatically invoked when the `CTest` module is included, except if the `BUILD_SETTING` option is turned off.

=== The ctest command
NOTE: The `ctest` executable is the CMake test driven program. CMake-generated build trees create for projects that use the `enable_testing()` and `add_test` commands have testing support. This program will run the tests and report result.